version: "3.8"

services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        command: python app.py run -h 0.0.0.0
        volumes:
            - ./:/usr/src/
        ports:
            - 5000:5000
        env_file:
            - .env
        depends_on:
            - db
    db:
        image: postgres:13.2
        container_name: db_${NAME_DB}
        hostname: db_film_collection
        restart: always
        env_file:
            - .env
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - db-data:/var/lib/postgresql/data
        ports:
            - 5432:5432

volumes:
   db-data: