version: "3.8"

services:
    web:
        build: .
        command: python app.py run -h 0.0.0.0
        volumes:
            - ./:/usr/src/app/
        ports:
            - 5000:5000
        env_file:
            - ./.env.list
    db:
        image: postgres:13.2
        restart: always
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            PGDATA: /var/lib/postgresql/data
        volumes:
            - db-data:/var/lib/postgresql/data
        ports:
            - 5432:5432
        env_file:
            - ./.env.list

volumes:
   db-data: