"""empty message

Revision ID: e13a85201c28
Revises: 6d4797afb4f9
Create Date: 2021-07-17 00:37:00.193100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e13a85201c28'
down_revision = '6d4797afb4f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_film_rating'), 'film', ['rating'], unique=False)
    op.create_index(op.f('ix_film_release_date'), 'film', ['release_date'], unique=False)
    op.drop_constraint('user_username_key', 'user', type_='unique')
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.create_unique_constraint('user_username_key', 'user', ['username'])
    op.drop_index(op.f('ix_film_release_date'), table_name='film')
    op.drop_index(op.f('ix_film_rating'), table_name='film')
    # ### end Alembic commands ###
